modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "spies-disguise"
version = "${version}"
displayName = "Spies Disguise"
authors = "Codiak540"
description = '''
Adds usefull Spy-related Items to Minecraft!
'''
#logoFile = ""

[[dependencies.spies-disguise]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spies-disguise]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spies-disguise]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
